[package]
name = "demo_native"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
napi-ohos = { workspace = true, features = ["tokio_rt"] }
napi-derive-ohos = { workspace = true }

openharmony-ability = { workspace = true }
openharmony-ability-derive = { workspace = true }
openharmony-ability-plugin-app-control = { workspace = true }
openharmony-ability-plugin-clipboard = { workspace = true }
openharmony-ability-plugin-menu = { workspace = true }
openharmony-ability-plugin-permission = { workspace = true }
openharmony-ability-plugin-statusbar = { workspace = true }
openharmony-ability-plugin-updater = { workspace = true }
openharmony-ability-plugin-version = { workspace = true }
openharmony-ability-plugin-webview = { workspace = true }
openharmony-ability-plugin-window = { workspace = true }
ohos-hilog-binding = { workspace = true }
futures-channel = { workspace = true }
futures-executor = "0.3"
http = { workspace = true }
log = "0.4"

[build-dependencies]
napi-build-ohos = { workspace = true }
