/* auto-generated by OHOS-RS */
/* eslint-disable */

export interface PermissionRequestPayload {
  permissions: Array<string>;
}
export interface PermissionResponsePayload {
  codes: Array<number>;
}

export interface WebviewAcknowledgement {
  accepted: boolean;
}

/**
 * Event subscriptions derived from Rust callback declarations before a WebView is created.
 *
 * This is transport state, not an ArkTS callback reference. The ArkTS host uses it only to bind
 * the corresponding ArkWeb delegate/event hooks for the new controller.
 */
export interface WebviewCallbackOptions {
  navigationIntercept: boolean;
  downloadStart: boolean;
  downloadEnd: boolean;
  titleChange: boolean;
}

/** Controller lifecycle signal delivered directly from the ArkTS WebView host. */
export interface WebviewControllerEvent {
  id: string;
}

export interface WebviewControllerRequest {
  id: string;
  slotId: string;
  visible?: boolean;
  color?: string;
  url?: string;
  html?: string;
  headers?: Record<string, string>;
  zoom?: number;
}

export interface WebviewCreateRequest {
  id: string;
  slotId: string;
  url?: string;
  html?: string;
  style: WebviewStyle;
  javascriptEnabled?: boolean;
  devtools?: boolean;
  userAgent?: string;
  autoplay?: boolean;
  initializationScripts?: Array<WebviewInitializationScript>;
  headers?: Record<string, string>;
  /**
   * Restores the legacy creation-time transparent-background policy. An explicit style
   * background color takes precedence.
   */
  transparent?: boolean;
  eventOptions: WebviewCallbackOptions;
}

export interface WebviewCreateResponse {
  id: string;
  slotId: string;
}

/** Completion notification delivered directly through a named N-API callback. */
export interface WebviewDownloadEndEvent {
  id: string;
  url: string;
  tempPath?: string;
  success: boolean;
}

/** Request delivered synchronously before ArkWeb starts a download. */
export interface WebviewDownloadStartRequest {
  id: string;
  url: string;
  tempPath?: string;
}

/** Immediate download admission and optional replacement destination. */
export interface WebviewDownloadStartResponse {
  allow: boolean;
  tempPath?: string;
}

/** Engine lifecycle signal delivered directly from the ArkTS WebView host. */
export interface WebviewEngineLifecycleEvent {
  phase: string;
}

/** Response used by one-way named N-API notifications sent directly from ArkTS. */
export interface WebviewEventAcknowledgement {
  accepted: boolean;
}

/** A document-start script and the URL rules for pages where ArkWeb may inject it. */
export interface WebviewInitializationScript {
  script: string;
  scriptRules: Array<string>;
}

/** Request delivered synchronously when ArkWeb asks whether a navigation should be intercepted. */
export interface WebviewNavigationRequest {
  id: string;
  url: string;
}

/** Synchronous navigation decision. A true value retains ArkWeb's existing intercept semantics. */
export interface WebviewNavigationResponse {
  intercept: boolean;
}

export interface WebviewScriptRequest {
  id: string;
  slotId: string;
  script: string;
}

export interface WebviewScriptResponse {
  result?: string;
}

export interface WebviewStringResponse {
  value?: string;
}

export interface WebviewStyle {
  x?: number | string;
  y?: number | string;
  visible?: boolean;
  backgroundColor?: string;
}

/** Title-change notification delivered directly through a named N-API callback. */
export interface WebviewTitleChangeEvent {
  id: string;
  title: string;
}

/**
 * This is passed to ArkTS as a real N-API object, not as JSON. The explicit bridge name makes
 * the contract stable even if the Rust struct/module name changes.
 */
export interface DemoProfile {
  userId: string;
  visitCount: number;
}

export interface LoginPublishResponse {
  published: boolean;
  module: string;
}

export interface LoginRequest {
  provider: string;
  scopes: Array<string>;
}

export interface LoginResponse {
  userId: string;
  displayName: string;
  accessToken: string;
  expiresAtMs: number;
}

export interface MainThreadInspectRequest {
  requested: boolean;
}

export interface MainThreadInspectResponse {
  module: string;
  sessionId: string;
  uiContextReady: boolean;
  execution: string;
}

/**
 * Creates a WebView through the WebView plugin. The ArkTS plugin mounts only into the named
 * business-owned BridgeNodeHost slot; it does not touch DefaultXComponent internals.
 */
export declare function createDemoWebview(): Promise<void>;

/** Bytes travel through the bridge as a Uint8Array, not a JSON number array or Base64 string. */
export declare function demoPluginBytes(): Promise<Array<number>>;

/** Worker -> TSFN -> ArkTS async plugin -> Rust future. */
export declare function demoPluginLogin(): Promise<string>;

/**
 * A `#[napi(object)]` value crosses the bridge directly and keeps its explicit `demo.Profile`
 * type identity at the ArkTS plugin boundary.
 */
export declare function demoPluginProfile(): Promise<DemoProfile>;

/** `String` travels as the named `std.string` N-API type, without JSON serialization. */
export declare function demoPluginString(): Promise<string>;

/** Synchronous plugins remain scoped to the N-API main-thread `Env`. */
export declare function demoPluginSyncContext(): string;

/**
 * Worker -> TSFN -> ArkTS sync plugin. The same `demo.main-thread` plugin is invoked from a
 * Rust worker; execution still happens on the ArkTS main thread and the named response is
 * marshalled back over TSFN.
 */
export declare function demoPluginSyncFromWorker(): Promise<string>;

/** PR #65: opens an external URL through `ohos.url` / `context.openLink`. */
export declare function demoOpenUrl(): Promise<void>;

/** PR #65: open-file dialog through `ohos.files` (multi-select + text/image filters). */
export declare function demoFileDialogOpen(): Promise<Array<string>>;

/** PR #65: save-file dialog through `ohos.files` with a PDF filter. */
export declare function demoFileDialogSave(): Promise<Array<string>>;

/**
 * `ohos.resource` plugin demo: whether the ArkTS wrapper has pushed the native resource manager
 * on `ability-create` (installed through the inbound `resource-manager-ready` event).
 */
export declare function demoResourceManagerReady(): boolean;

/**
 * `ohos.resource` plugin demo: top-level raw file directory entry count read through the native
 * resource manager, or -1 before the wrapper has pushed.
 */
export declare function demoResourceRawDirCount(): number;

export declare function demoRequestPermissionFromMainThread(): Promise<Array<number>>;

/**
 * Proves the Rust → WebView JavaScript path. The bridge waits for `onControllerAttached` before
 * calling ArkTS `WebviewController.runJavaScript`.
 */
export declare function evaluateDemoWebviewScript(): Promise<string>;

export declare function init(context?: AbilityInitContext): ApplicationLifecycle;

export declare function onBackPressIntercept(): boolean;

/** r" ArkTS-only lifecycle transitions, currently UI-context readiness transitions. */
export declare function onBridgeLifecycle(kind: string): void;

/**
 * r" Synchronous ArkTS platform callback -> Rust plugin decision port.
 * r"
 * r" The N-API value is scoped to this call and the returned value must be produced
 * r" before ArkTS resumes the originating platform callback. It is the dedicated
 * r" typed inbound event port for ArkTS plugins.
 */
export declare function onBridgeSyncEvent(
  pluginId: string,
  event: string,
  requestTypeName: string,
  responseTypeName: string,
  value: unknown,
): unknown;

export declare function render(bindings: object, slot: NodeContent): void;

export declare function setBackgroundColor(color: string): Promise<void>;

export declare function setVisible(visible: boolean): Promise<void>;

export declare function toggleBackPressIntercept(): boolean;

export interface AbilityInitContext {
  basePath?: string;
  prefPath?: string;
  preferredLocales?: string;
  moduleName?: string;
}

export interface ApplicationLifecycle {
  environmentCallback: EnvironmentCallback;
  windowStageEventCallback: WindowStageEventCallback;
  keyboardEventCallback: KeyboardCallback;
}

export interface EnvironmentCallback {
  onConfigurationUpdated: () => void;
  onMemoryLevel: (arg: number) => void;
}

export interface KeyboardCallback {
  onKeyboardHeightChange: (arg: number) => void;
}

export interface WindowStageEventCallback {
  onWindowStageCreate: () => void;
  onWindowStageDestroy: () => void;
  onAbilityCreate: (arg: string) => void;
  onAbilityDestroy: () => void;
  onAbilitySaveState: () => void;
  onAbilityRestoreState: () => void;
  onWindowStageEvent: (arg: number) => void;
  onWindowSizeChange: (arg: object) => void;
  onWindowRectChange: (arg: object) => void;
  onAvoidAreaChange: (arg: object) => void;
}
