/* auto-generated by OHOS-RS */
/* eslint-disable */

export declare function demoRequestPermissionFromMainThread(): Promise<Array<number>>

export declare function handleChange(): void

export declare function init(context?: AbilityInitContext | undefined | null): ApplicationLifecycle

export declare function onBackPressIntercept(): boolean

export declare function registerCustomProtocol(): void

export declare function render(helper: object, slot: NodeContent): void

export declare function setBackgroundColor(color: string): void

export declare function setVisible(visible: boolean): void

export declare function toggleBackPressIntercept(): boolean

