/* auto-generated by OHOS-RS */
/* eslint-disable */

export interface PermissionRequestPayload {
  permissions: Array<string>;
}

export interface PermissionResponsePayload {
  codes: Array<number>;
}

export interface UpdaterAcknowledgement {
  accepted: boolean;
}

export interface UpdaterCheckRequest {
  requested: boolean;
}

export interface UpdaterCheckResponse {
  result?: UpdaterCheckResult;
}

export interface UpdaterCheckResult {
  updateAvailable: boolean;
  currentVersion: string;
  version: string;
  body?: string;
  date?: string;
}

/** PDF export options. Field names match ArkTS `PdfConfiguration`. */
export interface PdfConfig {
  width?: number;
  height?: number;
  marginTop?: number;
  marginBottom?: number;
  marginLeft?: number;
  marginRight?: number;
  scale?: number;
  shouldPrintBackground?: boolean;
}

export interface WebviewAcknowledgement {
  accepted: boolean;
}

export interface WebviewBoolRequest {
  id: string;
  enabled?: boolean;
}

export interface WebviewBoolResponse {
  value: boolean;
}

export interface WebviewBoundsRequest {
  id: string;
  x: number;
  y: number;
  width: number;
  height: number;
}

/**
 * Event subscriptions derived from Rust callback declarations before a WebView is created.
 *
 * This is transport state, not an ArkTS callback reference. The ArkTS host uses it only to bind
 * the corresponding ArkWeb delegate/event hooks for the new controller.
 */
export interface WebviewCallbackOptions {
  navigationIntercept: boolean;
  downloadStart: boolean;
  downloadEnd: boolean;
  titleChange: boolean;
}

/** Controller lifecycle signal delivered directly from the ArkTS WebView host. */
export interface WebviewControllerEvent {
  id: string;
  /**
   * Process-unique ArkWeb controller tag generated by the ArkTS host. The public WebView ID
   * remains local to one plugin facade and is never used as a process-global platform key.
   */
  nativeTag: string;
}

export interface WebviewControllerRequest {
  id: string;
  visible?: boolean;
  color?: string;
  url?: string;
  html?: string;
  headers?: Record<string, string>;
  zoom?: number;
}

export interface WebviewCookieRequest {
  id: string;
  url: string;
  /** Set-Cookie format value, e.g. `name=value; Domain=...; Path=...`. */
  value: string;
}

export interface WebviewCreateRequest {
  id: string;
  /**
   * Optional opaque container handle issued by the built-in `ohos.node` plugin. When provided,
   * the ArkTS host appends the WebView FrameNode under that container instead of the current
   * plugin Host's DefaultXComponent root.
   */
  parentHandle?: number;
  url?: string;
  html?: string;
  style: WebviewStyle;
  javascriptEnabled?: boolean;
  devtools?: boolean;
  userAgent?: string;
  autoplay?: boolean;
  initializationScripts?: Array<WebviewInitializationScript>;
  headers?: Record<string, string>;
  /**
   * Restores the legacy creation-time transparent-background policy. An explicit style
   * background color takes precedence.
   */
  transparent?: boolean;
  eventOptions: WebviewCallbackOptions;
}

export interface WebviewCreateResponse {
  id: string;
}

/** Completion notification delivered directly through a named N-API callback. */
export interface WebviewDownloadEndEvent {
  id: string;
  /** Process-unique controller generation used to reject callbacks from a replaced WebView. */
  nativeTag: string;
  url: string;
  tempPath?: string;
  success: boolean;
}

/** Request delivered synchronously before ArkWeb starts a download. */
export interface WebviewDownloadStartRequest {
  id: string;
  /** Process-unique controller generation used to reject callbacks from a replaced WebView. */
  nativeTag: string;
  url: string;
  tempPath?: string;
}

/** Immediate download admission and optional replacement destination. */
export interface WebviewDownloadStartResponse {
  allow: boolean;
  tempPath?: string;
}

/** Engine lifecycle signal delivered directly from the ArkTS WebView host. */
export interface WebviewEngineLifecycleEvent {
  phase: string;
  /**
   * Process-global scheme set sealed before ArkWeb initialization. A facade activated after
   * the engine started may join only when every local declaration already exists in this set
   * with identical options.
   */
  schemes: Array<WebviewSchemeDeclaration>;
}

export interface WebviewEngineLifecycleResponse {
  accepted: boolean;
  schemes: Array<WebviewSchemeDeclaration>;
}

/** Response used by one-way named N-API notifications sent directly from ArkTS. */
export interface WebviewEventAcknowledgement {
  accepted: boolean;
}

/** A document-start script and the URL rules for pages where ArkWeb may inject it. */
export interface WebviewInitializationScript {
  script: string;
  scriptRules: Array<string>;
}

/** Request delivered synchronously when ArkWeb asks whether a navigation should be intercepted. */
export interface WebviewNavigationRequest {
  id: string;
  /** Process-unique controller generation used to reject callbacks from a replaced WebView. */
  nativeTag: string;
  url: string;
}

/** Synchronous navigation decision. A true value retains ArkWeb's existing intercept semantics. */
export interface WebviewNavigationResponse {
  intercept: boolean;
}

export interface WebviewPdfRequest {
  id: string;
  path: string;
  config?: PdfConfig;
}

export interface WebviewSchemeDeclaration {
  scheme: string;
  options: number;
}

export interface WebviewScriptRequest {
  id: string;
  script: string;
}

export interface WebviewScriptResponse {
  result?: string;
}

export interface WebviewSnapshotRequest {
  id: string;
}

export interface WebviewSnapshotResponse {
  rgba?: Array<number>;
  width: number;
  height: number;
}

export interface WebviewStringResponse {
  value?: string;
}

export interface WebviewStyle {
  x?: number | string;
  y?: number | string;
  /**
   * Optional width override. Defaults to the full container size; numbers are vp, strings are
   * ArkUI length expressions (for example "30%").
   */
  width?: number | string;
  /**
   * Optional height override. Defaults to the full container size; numbers are vp, strings are
   * ArkUI length expressions. Combined with `y` (for example y = "70%", height = "30%") a
   * WebView can be rendered in a corner or along one edge instead of full-screen.
   */
  height?: number | string;
  visible?: boolean;
  backgroundColor?: string;
}

/** Title-change notification delivered directly through a named N-API callback. */
export interface WebviewTitleChangeEvent {
  id: string;
  /** Process-unique controller generation used to reject callbacks from a replaced WebView. */
  nativeTag: string;
  title: string;
}

/**
 * This is passed to ArkTS as a real N-API object, not as JSON. The explicit bridge name makes
 * the contract stable even if the Rust struct/module name changes.
 */
export interface DemoProfile {
  userId: string;
  visitCount: number;
}

export interface LoginPublishResponse {
  published: boolean;
}

export interface LoginRequest {
  provider: string;
  scopes: Array<string>;
}

export interface LoginResponse {
  userId: string;
  displayName: string;
  accessToken: string;
  expiresAtMs: number;
}

export interface MainThreadInspectRequest {
  requested: boolean;
}

export interface MainThreadInspectResponse {
  sessionId: string;
  uiContextReady: boolean;
  execution: string;
}

/**
 * Renders a WebView pinned to the bottom edge of the session surface instead of full-screen:
 * `y = "70%"` + `height = "30%"` keeps the full-bleed default intact for WebViews without an
 * explicit style. This proves the normalized model gives the caller full layout control.
 */
export declare function createBottomDemoWebview(): Promise<void>;

/**
 * Demonstrates the normalized composition model: an RS-layer container node is created through
 * the built-in ohos.node plugin, the WebView FrameNode is attached under it via
 * `parent_node(...)`, and the whole tree is mounted into the module/component root.
 */
export declare function createComposedDemoWebview(): Promise<void>;

/**
 * Creates a WebView through the WebView plugin. Without a parent container handle the ArkTS
 * host mounts the WebView FrameNode into this module's component root (full-bleed default); it never touches
 * DefaultXComponent internals.
 */
export declare function createDemoWebview(): Promise<void>;

/** PR #63 capability demo: query the API 21+ autostart state. */
export declare function demoAutostartIsEnabled(): Promise<boolean>;

/** PR #63 capability demo: open the system app-launch management page. */
export declare function demoAutostartOpenSettings(): Promise<void>;

/** PR #63 capability demo: clipboard image write. */
export declare function demoClipboardWriteImage(): Promise<void>;

/** PR #63 capability demo: create an OS sub-window through `ohos.window`. */
export declare function demoCreateOsWindow(): Promise<number>;

/** PR #63 capability demo: destroy one OS sub-window created by `demo_create_os_window`. */
export declare function demoDestroyOsWindow(windowId: number): Promise<void>;

/** PR #65 capability demo: open-file dialog through `ohos.files`. */
export declare function demoFileDialogOpen(): Promise<Array<string>>;

/** PR #65 capability demo: save-file dialog through `ohos.files`. */
export declare function demoFileDialogSave(): Promise<Array<string>>;

/** PR #63 capability demo: context popup menu at given coordinates. */
export declare function demoMenuPopup(x: number, y: number): Promise<void>;

/** PR #63 capability demo: menu system (menubar + popup) through `ohos.menu`. */
export declare function demoMenuSetMenubar(): Promise<void>;

/** PR #65 capability demo: open an external URL through `ohos.url`. */
export declare function demoOpenUrl(): Promise<void>;

/** Bytes travel through the bridge as a Uint8Array, not a JSON number array or Base64 string. */
export declare function demoPluginBytes(): Promise<Array<number>>;

/** Worker -> TSFN -> ArkTS async plugin -> Rust future. */
export declare function demoPluginLogin(): Promise<string>;

/**
 * A `#[napi(object)]` value crosses the bridge directly and keeps its explicit `demo.Profile`
 * type identity at the ArkTS plugin boundary.
 */
export declare function demoPluginProfile(): Promise<DemoProfile>;

/** `String` travels as the named `std.string` N-API type, without JSON serialization. */
export declare function demoPluginString(): Promise<string>;

/** Synchronous plugins remain scoped to the N-API main-thread `Env`. */
export declare function demoPluginSyncContext(): string;

/**
 * Worker -> TSFN -> ArkTS sync plugin -> Rust future. The same `demo.main-thread` plugin is
 * invoked from a Rust worker; execution still happens on the ArkTS main thread and the named
 * response is marshalled back over TSFN.
 */
export declare function demoPluginSyncFromWorker(): Promise<string>;

export declare function demoRequestPermissionFromMainThread(): Promise<Array<number>>;

/**
 * Demo: reports whether the `ohos.resource` wrapper has pushed the native resource manager
 * (it is installed from the Ability-scoped ArkTS `onInstall`, before UI rendering is required).
 */
export declare function demoResourceManagerReady(): boolean;

/**
 * Demo: reads the top-level raw file directory through the native resource manager. Returns
 * the number of entries, or -1 when the `ohos.resource` plugin has not installed yet.
 */
export declare function demoResourceRawDirCount(): number;

/** PR #63 capability demo: restart the app (cooldown 3s). */
export declare function demoRestart(): void;

/** PR #63 capability demo: switch color mode (0 dark / 1 light / 2 system). */
export declare function demoSetColorMode(mode: number): void;

/** PR #63 capability demo: system tray item with menu groups. */
export declare function demoStatusbarAdd(): Promise<void>;

/** PR #63 capability demo: remove the process-level status bar item. */
export declare function demoStatusbarRemove(): Promise<void>;

/** PR #63 capability demo: AppGallery update check. */
export declare function demoUpdaterCheck(): Promise<string | null>;

/** PR #63 capability demo: device version + capability queries. */
export declare function demoVersionInfo(): string;

export declare function disposeAllRenders(): void;

/**
 * r" Releases the Ability-session transport without touching this module's independent
 * r" DefaultXComponent render owner. Stale owners are ignored.
 */
export declare function disposeBridge(bridgeOwner: string): void;

export declare function disposeRender(renderOwner: string): void;

/**
 * Proves the Rust → WebView JavaScript path. The bridge waits for `onControllerAttached` before
 * calling ArkTS `WebviewController.runJavaScript`.
 */
export declare function evaluateDemoWebviewScript(): Promise<string>;

export declare function init(
  bindings: object,
  bridgeOwner: string,
  context?: AbilityInitContext,
): ApplicationLifecycle;

export declare function onBackPressIntercept(): boolean;

/** r" ArkTS-only lifecycle transitions, currently UI-context readiness transitions. */
export declare function onBridgeLifecycle(kind: string): void;

/**
 * r" Synchronous ArkTS platform callback -> Rust plugin decision port.
 * r"
 * r" The N-API value is scoped to this call and the returned value must be produced
 * r" before ArkTS resumes the originating platform callback. It is the dedicated
 * r" typed inbound event port for ArkTS plugins.
 */
export declare function onBridgeSyncEvent(
  pluginId: string,
  event: string,
  requestTypeName: string,
  responseTypeName: string,
  value: unknown,
): unknown;

export declare function render(slot: NodeContent, renderOwner: string): void;

export declare function setBackgroundColor(color: string): Promise<void>;

export declare function setVisible(visible: boolean): Promise<void>;

export declare function toggleBackPressIntercept(): boolean;

export interface UrlOpenRequest {
  url: string;
}

export interface UrlOpenResponse {
  accepted: boolean;
}

export interface ClipboardAcknowledgement {
  accepted: boolean;
}

export interface ClipboardImageRequest {
  /** RGBA-8888 pixel data, length must equal `width * height * 4`. */
  rgba: Array<number>;
  width: number;
  height: number;
}

/**
 * One suffix filter group: a display name plus `;`-separated suffixes (e.g. `"md"`).
 * The pattern stays structured; the ArkTS plugin converts it to the picker grammar.
 */
export interface FileDialogFilter {
  name?: string;
  pattern?: string;
}

export interface FileDialogOptions {
  /** One of [`dialog_type`] constants. */
  dialogType: string;
  allowMany: boolean;
  defaultLocation?: string;
  filters: Array<FileDialogFilter>;
}

export interface FileDialogResponse {
  /** Selected file URIs. */
  files: Array<string>;
  /** Selected filter index, or -1 when the platform does not report one. */
  filter: number;
}

export interface ResourceManagerReadyResponse {
  accepted: boolean;
}

export interface AbilityInitContext {
  basePath?: string;
  prefPath?: string;
  preferredLocales?: string;
  moduleName?: string;
  /** OpenHarmony base API Level provided by ArkTS `deviceInfo.sdkApiVersion`. */
  sdkApiVersion?: number;
  /** HarmonyOS distribution version provided by ArkTS `deviceInfo.distributionOSApiVersion`. */
  distributionOSApiVersion?: number;
}

export interface ApplicationLifecycle {
  bridgePlugins: Array<BridgePluginDeclaration>;
  environmentCallback: EnvironmentCallback;
  windowStageEventCallback: WindowStageEventCallback;
  keyboardEventCallback: KeyboardCallback;
}

/**
 * Structural declaration exported to ArkTS after the native module has configured its Rust
 * plugin registry. The host uses this to select the matching factory automatically and to
 * validate the parts of the contract that affect scheduling. Request and response ABI identity
 * remains pinned by each named N-API type.
 */
export interface BridgePluginDeclaration {
  id: string;
  execution: string;
  requires: Array<string>;
}

export interface EnvironmentCallback {
  onConfigurationUpdated: () => void;
  onMemoryLevel: (arg: number) => void;
}

export interface KeyboardCallback {
  onKeyboardHeightChange: (arg: number) => void;
}

export interface NodeAcknowledgement {
  accepted: boolean;
}

/** Appends the node of `child_handle` under the node of `parent_handle`. */
export interface NodeAppendChildRequest {
  parentHandle: number;
  childHandle: number;
}

/** Request marker for `create-container`: the response carries the new handle. */
export interface NodeCreateContainerRequest {}

/** Detaches a handle-owned node from its parent and disposes it. */
export interface NodeDisposeRequest {
  handle: number;
}

/** Opaque handle of a container `FrameNode` created in ArkTS. */
export interface NodeHandleResponse {
  handle: number;
}

/** Appends a handle-owned node to this module's component root. */
export interface NodeMountIntoRootRequest {
  handle: number;
}

export interface WindowStageEventCallback {
  onWindowStageCreate: () => void;
  onWindowStageDestroy: () => void;
  onAbilityCreate: (arg: string) => void;
  onAbilityDestroy: () => void;
  onAbilitySaveState: () => void;
  onAbilityRestoreState: () => void;
  onWindowStageEvent: (arg: number) => void;
  onWindowSizeChange: (arg: object) => void;
  onWindowRectChange: (arg: object) => void;
  onAvoidAreaChange: (arg: object) => void;
  onNewWant: (arg: object) => void;
  onAbilityCreateWithWant: (arg: object) => void;
}

export interface AutostartAcknowledgement {
  accepted: boolean;
}

export interface AutostartRequest {
  requested: boolean;
}

export interface AutostartStatusResponse {
  enabled: boolean;
  supported: boolean;
}

/** Optional application metadata for the "about" menu item. */
export interface AboutMetadataData {
  name?: string;
  version?: string;
  shortVersion?: string;
  authors?: Array<string>;
  comments?: string;
  copyright?: string;
  license?: string;
  website?: string;
}

export interface MenuAcknowledgement {
  accepted: boolean;
}

export interface MenuBarRequest {
  windowId: string;
  items: Array<MenuItemData>;
}

/** ArkTS → Rust menu click request (named N-API main-thread event). */
export interface MenuClickRequest {
  id: string;
  windowId?: string;
}

export interface MenuClickResponse {
  accepted: boolean;
}

/** One recursive menu entry. `submenu_items` nests child entries. */
export interface MenuItemData {
  id: string;
  /** One of [`item_kind`] constants. */
  itemType: string;
  text?: string;
  enabled?: boolean;
  accelerator?: string;
  /** One of the predefined action names, e.g. `copy`, `paste`, `quit`, `minimize`. */
  predefinedType?: string;
  checked?: boolean;
  icon?: string;
  nativeIcon?: string;
  submenuItems?: Array<MenuItemData>;
  aboutMetadata?: AboutMetadataData;
}

export interface MenuPopupRequest {
  windowId: string;
  x?: number;
  y?: number;
  items: Array<MenuItemData>;
}

export interface MenuVisibilityRequest {
  windowId: string;
  visible: boolean;
}

export interface AvoidAreaRequest {
  areaType: number;
}

export interface AvoidAreaResponse {
  area: RawAvoidArea;
}

export interface RawAvoidArea {
  visible: boolean;
  leftRect: RawRect;
  topRect: RawRect;
  rightRect: RawRect;
  bottomRect: RawRect;
}

export interface RawRect {
  top: number;
  left: number;
  width: number;
  height: number;
}

export interface WindowAcknowledgement {
  accepted: boolean;
}

export interface WindowBlurRequest {
  windowId: number;
  radius: number;
}

export interface WindowColorRequest {
  windowId: number;
  color: number;
}

export interface WindowCreateRequest {
  name: string;
  width: number;
  height: number;
  x: number;
  y: number;
  /** Whether to show window decorations (title bar, drag area, close button). */
  decorations: boolean;
  /** Fully transparent window background. */
  transparent: boolean;
  /** Window background color in 0xAARRGGBB format; ignored when `transparent` is true. */
  backgroundColor?: number;
}

export interface WindowCreateResponse {
  windowId: number;
}

export interface WindowDecorationsRequest {
  windowId: number;
  decorations: boolean;
}

export interface WindowFocusableRequest {
  windowId: number;
  focusable: boolean;
}

export interface WindowIdRequest {
  windowId: number;
}

export interface WindowMoveRequest {
  windowId: number;
  x: number;
  y: number;
}

export interface WindowResizeRequest {
  windowId: number;
  width: number;
  height: number;
}

export interface WindowStateResponse {
  value: boolean;
}

/** Quick-operation card shown when the tray item is hovered. */
export interface QuickOperationData {
  abilityName: string;
  title: string;
  height: number;
  /** ArkTS/HAP module containing the target extension Ability; unrelated to native bridge hosts. */
  moduleName?: string;
  loadingStatus?: boolean;
}

export interface StatusBarAcknowledgement {
  accepted: boolean;
}

export interface StatusBarActionRequest {
  /** One of the predefined action names, e.g. `show` or `quit`. */
  action: string;
}

export interface StatusBarAddRequest {
  item: StatusBarItemData;
}

/** ArkTS → Rust tray icon click request (named N-API main-thread event). */
export interface StatusBarClickRequest {
  clickType: string;
}

export interface StatusBarClickResponse {
  accepted: boolean;
}

/** One tray icon with optional white/black RGBA pixel variants. */
export interface StatusBarIconData {
  whiteRgba?: Array<number>;
  blackRgba?: Array<number>;
  size: number;
}

export interface StatusBarIconRequest {
  icon: StatusBarIconData;
}

/** Full tray item description. */
export interface StatusBarItemData {
  icons: StatusBarIconData;
  quickOperation: QuickOperationData;
  statusBarGroupMenu?: Array<Array<StatusBarMenuItemData>>;
  hoverTips?: string;
}

/** Menu action launched when a tray menu item is activated. */
export interface StatusBarMenuActionData {
  abilityName: string;
  /** ArkTS/HAP module used in the platform Want; unrelated to native bridge hosts. */
  moduleName?: string;
  menuCode?: string;
  notifyOnly?: boolean;
}

/** ArkTS → Rust tray menu click request (named N-API main-thread event). */
export interface StatusBarMenuClickRequest {
  menuCode: string;
}

/** One tray menu entry with an optional sub-menu group. */
export interface StatusBarMenuItemData {
  title: string;
  menuCode?: string;
  subMenu?: Array<StatusBarSubMenuItemData>;
  menuAction?: StatusBarMenuActionData;
  selected?: boolean;
  iconRgba?: Array<number>;
  iconWidth?: number;
  iconHeight?: number;
}

export interface StatusBarMenuRequest {
  groups: Array<Array<StatusBarMenuItemData>>;
}

/** One tray sub-menu entry. */
export interface StatusBarSubMenuItemData {
  subTitle: string;
  menuCode?: string;
  menuAction: StatusBarMenuActionData;
  selected?: boolean;
}

export interface StatusBarTipsRequest {
  tips: string;
}

export interface ColorModeRequest {
  /** 0 = dark, 1 = light, 2 = follow system (`ConfigurationConstant.ColorMode`). */
  mode: number;
}

export interface ColorModeResponse {
  accepted: boolean;
}

export interface RestartRequest {
  requested: boolean;
}

export interface RestartResponse {
  accepted: boolean;
}

/** Marker retained for API symmetry; all actions are synchronous. */
export interface TerminateRequest {
  code: number;
}

export interface TerminateResponse {
  accepted: boolean;
}

export interface VersionRequest {
  syscap?: string;
}

export interface VersionResponse {
  value: number;
  result?: boolean;
}
