/* auto-generated by OHOS-RS */
/* eslint-disable */

export interface PermissionRequestPayload {
  permissions: Array<string>;
}

export interface PermissionResponsePayload {
  codes: Array<number>;
}

export interface WebviewAcknowledgement {
  accepted: boolean;
}

/**
 * Event subscriptions derived from Rust callback declarations before a WebView is created.
 *
 * This is transport state, not an ArkTS callback reference. The ArkTS host uses it only to bind
 * the corresponding ArkWeb delegate/event hooks for the new controller.
 */
export interface WebviewCallbackOptions {
  navigationIntercept: boolean;
  downloadStart: boolean;
  downloadEnd: boolean;
  titleChange: boolean;
}

/** Controller lifecycle signal delivered directly from the ArkTS WebView host. */
export interface WebviewControllerEvent {
  id: string;
}

export interface WebviewControllerRequest {
  id: string;
  visible?: boolean;
  color?: string;
  url?: string;
  html?: string;
  headers?: Record<string, string>;
  zoom?: number;
}

export interface WebviewCreateRequest {
  id: string;
  /**
   * Optional window surface key the WebView mounts into. Defaults to `"main"` (the default
   * window's `DefaultXComponent`); sub-window instances register under their own `windowKey`.
   */
  windowKey?: string;
  /**
   * Optional opaque container handle issued by the built-in `ohos.node` plugin. When provided,
   * the ArkTS host appends the WebView FrameNode under that container instead of the window
   * root, so an RS-layer node tree can adopt WebViews as children. Absent = full-bleed window
   * root mount.
   */
  parentHandle?: number;
  url?: string;
  html?: string;
  style: WebviewStyle;
  javascriptEnabled?: boolean;
  devtools?: boolean;
  userAgent?: string;
  autoplay?: boolean;
  initializationScripts?: Array<WebviewInitializationScript>;
  headers?: Record<string, string>;
  /**
   * Restores the legacy creation-time transparent-background policy. An explicit style
   * background color takes precedence.
   */
  transparent?: boolean;
  eventOptions: WebviewCallbackOptions;
}

export interface WebviewCreateResponse {
  id: string;
}

/** Completion notification delivered directly through a named N-API callback. */
export interface WebviewDownloadEndEvent {
  id: string;
  url: string;
  tempPath?: string;
  success: boolean;
}

/** Request delivered synchronously before ArkWeb starts a download. */
export interface WebviewDownloadStartRequest {
  id: string;
  url: string;
  tempPath?: string;
}

/** Immediate download admission and optional replacement destination. */
export interface WebviewDownloadStartResponse {
  allow: boolean;
  tempPath?: string;
}

/** Engine lifecycle signal delivered directly from the ArkTS WebView host. */
export interface WebviewEngineLifecycleEvent {
  phase: string;
}

/** Response used by one-way named N-API notifications sent directly from ArkTS. */
export interface WebviewEventAcknowledgement {
  accepted: boolean;
}

/** A document-start script and the URL rules for pages where ArkWeb may inject it. */
export interface WebviewInitializationScript {
  script: string;
  scriptRules: Array<string>;
}

/** Request delivered synchronously when ArkWeb asks whether a navigation should be intercepted. */
export interface WebviewNavigationRequest {
  id: string;
  url: string;
}

/** Synchronous navigation decision. A true value retains ArkWeb's existing intercept semantics. */
export interface WebviewNavigationResponse {
  intercept: boolean;
}

export interface WebviewScriptRequest {
  id: string;
  script: string;
}

export interface WebviewScriptResponse {
  result?: string;
}

export interface WebviewStringResponse {
  value?: string;
}

export interface WebviewStyle {
  x?: number | string;
  y?: number | string;
  /**
   * Optional width override. Defaults to the full container size; numbers are vp, strings are
   * ArkUI length expressions (for example "30%").
   */
  width?: number | string;
  /**
   * Optional height override. Defaults to the full container size; numbers are vp, strings are
   * ArkUI length expressions. Combined with `y` (for example y = "70%", height = "30%") a
   * WebView can be rendered in a corner or along one edge instead of full-screen.
   */
  height?: number | string;
  visible?: boolean;
  backgroundColor?: string;
}

/** Title-change notification delivered directly through a named N-API callback. */
export interface WebviewTitleChangeEvent {
  id: string;
  title: string;
}

/**
 * This is passed to ArkTS as a real N-API object, not as JSON. The explicit bridge name makes
 * the contract stable even if the Rust struct/module name changes.
 */
export interface DemoProfile {
  userId: string;
  visitCount: number;
}

export interface LoginPublishResponse {
  published: boolean;
  module: string;
}

export interface LoginRequest {
  provider: string;
  scopes: Array<string>;
}

export interface LoginResponse {
  userId: string;
  displayName: string;
  accessToken: string;
  expiresAtMs: number;
}

export interface MainThreadInspectRequest {
  requested: boolean;
}

export interface MainThreadInspectResponse {
  module: string;
  sessionId: string;
  uiContextReady: boolean;
  execution: string;
}

/**
 * Renders a WebView pinned to the bottom edge of the session surface instead of full-screen:
 * `y = "70%"` + `height = "30%"` keeps the full-bleed default intact for WebViews without an
 * explicit style. This proves the normalized model gives the caller full layout control.
 */
export declare function createBottomDemoWebview(): Promise<void>;

/**
 * Demonstrates the normalized composition model: an RS-layer container node is created through
 * the built-in ohos.node plugin, the WebView FrameNode is attached under it via
 * `parent_node(...)`, and the whole tree is mounted into the session root.
 */
export declare function createComposedDemoWebview(): Promise<void>;

/**
 * Creates a WebView through the WebView plugin. Without a parent container handle the ArkTS
 * host mounts the WebView FrameNode into the session root (full-bleed default); it never touches
 * DefaultXComponent internals.
 */
export declare function createDemoWebview(): Promise<void>;

/**
 * Creates a WebView inside the sub-window surface (`window_key = "sub"`). The sub window page
 * places a second `DefaultXComponent({ windowKey: "sub" })`, and this WebView mounts into that
 * window's own node tree instead of the main window's.
 */
export declare function createSubWindowWebview(): Promise<void>;

/** PR #65 capability demo: open-file dialog through `ohos.files`. */
export declare function demoFileDialogOpen(): Promise<Array<string>>;

/** PR #65 capability demo: save-file dialog through `ohos.files`. */
export declare function demoFileDialogSave(): Promise<Array<string>>;

/** PR #65 capability demo: open an external URL through `ohos.url`. */
export declare function demoOpenUrl(): Promise<void>;

/** Bytes travel through the bridge as a Uint8Array, not a JSON number array or Base64 string. */
export declare function demoPluginBytes(): Promise<Array<number>>;

/** Worker -> TSFN -> ArkTS async plugin -> Rust future. */
export declare function demoPluginLogin(): Promise<string>;

/**
 * A `#[napi(object)]` value crosses the bridge directly and keeps its explicit `demo.Profile`
 * type identity at the ArkTS plugin boundary.
 */
export declare function demoPluginProfile(): Promise<DemoProfile>;

/** `String` travels as the named `std.string` N-API type, without JSON serialization. */
export declare function demoPluginString(): Promise<string>;

/** Synchronous plugins remain scoped to the N-API main-thread `Env`. */
export declare function demoPluginSyncContext(): string;

/**
 * Worker -> TSFN -> ArkTS sync plugin -> Rust future. The same `demo.main-thread` plugin is
 * invoked from a Rust worker; execution still happens on the ArkTS main thread and the named
 * response is marshalled back over TSFN.
 */
export declare function demoPluginSyncFromWorker(): Promise<string>;

export declare function demoRequestPermissionFromMainThread(): Promise<Array<number>>;

/**
 * Demo: reports whether the `ohos.resource` wrapper has pushed the native resource manager
 * (it is installed on `ui-context-ready` after the native module is rendered).
 */
export declare function demoResourceManagerReady(): boolean;

/**
 * Demo: reads the top-level raw file directory through the native resource manager. Returns
 * the number of entries, or -1 when the `ohos.resource` plugin has not installed yet.
 */
export declare function demoResourceRawDirCount(): number;

/**
 * Proves the Rust → WebView JavaScript path. The bridge waits for `onControllerAttached` before
 * calling ArkTS `WebviewController.runJavaScript`.
 */
export declare function evaluateDemoWebviewScript(): Promise<string>;

export declare function init(context?: AbilityInitContext): ApplicationLifecycle;

export declare function onBackPressIntercept(): boolean;

/** r" ArkTS-only lifecycle transitions, currently UI-context readiness transitions. */
export declare function onBridgeLifecycle(kind: string): void;

/**
 * r" Synchronous ArkTS platform callback -> Rust plugin decision port.
 * r"
 * r" The N-API value is scoped to this call and the returned value must be produced
 * r" before ArkTS resumes the originating platform callback. It is the dedicated
 * r" typed inbound event port for ArkTS plugins.
 */
export declare function onBridgeSyncEvent(
  pluginId: string,
  event: string,
  requestTypeName: string,
  responseTypeName: string,
  value: unknown,
): unknown;

export declare function render(bindings: object, slot: NodeContent): void;

export declare function setBackgroundColor(color: string): Promise<void>;

export declare function setVisible(visible: boolean): Promise<void>;

export declare function toggleBackPressIntercept(): boolean;

export interface UrlOpenRequest {
  url: string;
}

export interface UrlOpenResponse {
  accepted: boolean;
}

/**
 * One suffix filter group: a display name plus `;`-separated suffixes (e.g. `"md"`).
 * The pattern stays structured; the ArkTS plugin converts it to the picker grammar.
 */
export interface FileDialogFilter {
  name?: string;
  pattern?: string;
}

export interface FileDialogOptions {
  /** One of [`dialog_type`] constants. */
  dialogType: string;
  allowMany: boolean;
  defaultLocation?: string;
  filters: Array<FileDialogFilter>;
}

export interface FileDialogResponse {
  /** Selected file URIs. */
  files: Array<string>;
  /** Selected filter index, or -1 when the platform does not report one. */
  filter: number;
}

export interface ResourceManagerReadyResponse {
  accepted: boolean;
}

export interface AbilityInitContext {
  basePath?: string;
  prefPath?: string;
  preferredLocales?: string;
  moduleName?: string;
}

export interface ApplicationLifecycle {
  environmentCallback: EnvironmentCallback;
  windowStageEventCallback: WindowStageEventCallback;
  keyboardEventCallback: KeyboardCallback;
}

export interface EnvironmentCallback {
  onConfigurationUpdated: () => void;
  onMemoryLevel: (arg: number) => void;
}

export interface KeyboardCallback {
  onKeyboardHeightChange: (arg: number) => void;
}

export interface NodeAcknowledgement {
  accepted: boolean;
}

/** Appends the node of `child_handle` under the node of `parent_handle`. */
export interface NodeAppendChildRequest {
  parentHandle: number;
  childHandle: number;
  /** Window surface key; defaults to `"main"`. Parent and child must share the same window. */
  windowKey?: string;
}

/** Window-scoped request marker for `create-container`: the response carries the new handle. */
export interface NodeCreateContainerRequest {
  /** Window surface key; defaults to `"main"`. */
  windowKey?: string;
}

/** Detaches a handle-owned node from its parent and disposes it. */
export interface NodeDisposeRequest {
  handle: number;
  /** Window surface key; defaults to `"main"`. */
  windowKey?: string;
}

/** Opaque handle of a container `FrameNode` created in ArkTS. */
export interface NodeHandleResponse {
  handle: number;
}

/** Appends a handle-owned node to the window root. */
export interface NodeMountIntoRootRequest {
  handle: number;
  /** Window surface key; defaults to `"main"`. */
  windowKey?: string;
}

export interface WindowStageEventCallback {
  onWindowStageCreate: () => void;
  onWindowStageDestroy: () => void;
  onAbilityCreate: (arg: string) => void;
  onAbilityDestroy: () => void;
  onAbilitySaveState: () => void;
  onAbilityRestoreState: () => void;
  onWindowStageEvent: (arg: number) => void;
  onWindowSizeChange: (arg: object) => void;
  onWindowRectChange: (arg: object) => void;
  onAvoidAreaChange: (arg: object) => void;
}
