/* auto-generated by OHOS-RS */
/* eslint-disable */

export interface AbilityInitContext {
  basePath?: string
  prefPath?: string
  preferredLocales?: string
  moduleName?: string
  sdkApiVersion?: number
  distributionOSApiVersion?: number
}

export interface ApplicationLifecycle {
  environmentCallback: EnvironmentCallback
  windowStageEventCallback: WindowStageEventCallback
  keyboardEventCallback: KeyboardCallback
}

export interface EnvironmentCallback {
  onConfigurationUpdated: () => void
  onMemoryLevel: (arg: number) => void
}

export interface KeyboardCallback {
  onKeyboardHeightChange: (arg: number) => void
}

export interface WindowStageEventCallback {
  onWindowStageCreate: () => void
  onWindowStageDestroy: () => void
  onAbilityCreate: () => void
  onAbilityDestroy: () => void
  onAbilitySaveState: () => void
  onAbilityRestoreState: () => void
  onWindowStageEvent: (arg: number) => void
  onWindowSizeChange: (arg: object) => void
  onWindowRectChange: (arg: object) => void
  onAvoidAreaChange: (arg: object) => void
  onNewWant: (arg: { uri: string; parametersJson: string }) => void
}

export declare function isDesktopDevice(): boolean

